# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sangbin Lee - PortFolio Website
email: tkdqls1496@gmail.com
description: CFX / RIG artist (Houdini / Maya)
twitter_username: SANGBINLEE1993
github_username: SangBinLee93
minimal_mistakes_skin: mint
search: False

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
permalink: pretty
paginate: 4 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul # chatGPT

include:
   - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "SangBin Lee"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : |
      - CFX / RIG artist
      - Animation / Cinematic
      - Maya, Houdini, Unreal Engine
      - Vellum ( Hair, Cloth )
      - nHair, nCloth, Qualoth
      - Rig, 3D Math
      - Ragdoll Dynamics 
      - Python, PyMEL, PySide, MEL, VEX
      - Yeti, Xgen
      - Marvelous Designer
        
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lee93/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/SangBinLee93"
    - label: "twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/SANGBINLEE1993"
    - label: "tkdqls1496@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:tkdqls1496@gmail.com"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/"

# footer:
#   links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

# Collections
collections:
  Personal:
    output: true
    permalink: /:collection/:path/
  Animation:
    output: true
    permalink: /:collection/:path/
  VFX:
    output: true
    permalink: /:collection/:path/
  Script:
    output: true
    permalink: /:collection/:path/
  Commercial:
    output: true
    permalink: /:collection/:path/
  ETC:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      share: false
  # _Personal
  - scope:
      path: ""
      type: Personal
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _Animation
  - scope:
      path: ""
      type: Animation
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _VFX
  - scope:
      path: ""
      type: VFX
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _Script
  - scope:
      path: ""
      type: Script
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _Commercial
  - scope:
      path: ""
      type: Commercial
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _ETC
  - scope:
      path: ""
      type: ETC
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/